services:
  cli:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yii2_elfinder_php_cli
    image: yii2_elfinder_php84
    working_dir: /app
    volumes:
      - ./:/app
    tty: true
    stdin_open: true